-- SQL Script to Drop All Tables (in dependency order)

DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS CartItem;
DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS OrderItem;
DROP TABLE IF EXISTS `Order`;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Customer;
